import { DbTicketDetail } from "@/api/serviceDesk/ticket";

export const ticket: DbTicketDetail = {
  id: "sunghwan-portal-2026-5",
  ticket_number: "SP-2026-0005",
  created_at: "2026-04-02T06:03:14Z",
  updated_at: "2026-04-02T07:21:42Z",
  requester_id: "141",
  status: "Resolved",
  close_reason: null,
  priority: "high",
  risk_level: "high",
  assignee_id: ["41", "31"],
  merged_into_ticket_id: null,
  track_time_minutes: 105,
  last_comment_at: "2026-04-02T07:21:42Z",
  last_commenter_email: "Daniel.Kim@sunghwan-portal.dev",
  due_at: "2026-04-03T18:00:00Z",
  owner: false,
  assigned: false,
  active: true,
  scope: "PORTAL",
  category_id: "5",
  approval_step_id: null,
  subject: "Outbound shipping screen stuck on loading",
  content:
    "While processing outbound shipments, the shipping execution screen keeps showing only the loading icon and never completes.<br>Users in logistics cannot finish outbound shipping transactions.",
  email: {
    to: ["Evan.Seo@sunghwan-portal.dev", "Daniel.Kim@sunghwan-portal.dev"],
    cc: ["Victor.Rivera@sunghwan-portal.dev"],
    bcc: [],
  },
  files: [],
  images: [],
};
