import { DbJobField } from "@/api/organization/jobField/mapper";

export const jobFieldsMock: DbJobField[] = [
  /*  Head Office  */
  {
    job_field_id: 1,
    job_field_name: { en: "Head of Corporate Affairs" },
    job_field_description: { en: "" },
    job_field_department_id: 1,
    job_field_parent_id: 0,
    job_field_active: true,
  },
  {
    job_field_id: 2,
    job_field_name: { en: "HR Director" },
    job_field_description: { en: "" },
    job_field_department_id: 2,
    job_field_parent_id: 0,
    job_field_active: true,
  },
  {
    job_field_id: 3,
    job_field_name: { en: "HR Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 2,
    job_field_parent_id: 2,
    job_field_active: true,
  },
  {
    job_field_id: 4,
    job_field_name: { en: "HR Officer" },
    job_field_description: { en: "" },
    job_field_department_id: 2,
    job_field_parent_id: 3,
    job_field_active: true,
  },
  {
    job_field_id: 5,
    job_field_name: { en: "Finance Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 3,
    job_field_parent_id: 0,
    job_field_active: true,
  },
  {
    job_field_id: 6,
    job_field_name: { en: "Financial Controller" },
    job_field_description: { en: "" },
    job_field_department_id: 3,
    job_field_parent_id: 5,
    job_field_active: true,
  },
  {
    job_field_id: 7,
    job_field_name: { en: "Finance Officer" },
    job_field_description: { en: "" },
    job_field_department_id: 3,
    job_field_parent_id: 6,
    job_field_active: true,
  },
  {
    job_field_id: 8,
    job_field_name: { en: "Sales Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 4,
    job_field_parent_id: 0,
    job_field_active: true,
  },
  {
    job_field_id: 9,
    job_field_name: { en: "Account Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 4,
    job_field_parent_id: 8,
    job_field_active: true,
  },
  {
    job_field_id: 10,
    job_field_name: { en: "Sales Representative" },
    job_field_description: { en: "" },
    job_field_department_id: 4,
    job_field_parent_id: 9,
    job_field_active: true,
  },
  {
    job_field_id: 11,
    job_field_name: { en: "Customer Support Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 5,
    job_field_parent_id: 0,
    job_field_active: true,
  },
  {
    job_field_id: 12,
    job_field_name: { en: "Support Specialist" },
    job_field_description: { en: "" },
    job_field_department_id: 5,
    job_field_parent_id: 11,
    job_field_active: true,
  },
  {
    job_field_id: 13,
    job_field_name: { en: "Security Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 9,
    job_field_parent_id: 0,
    job_field_active: true,
  },
  {
    job_field_id: 14,
    job_field_name: { en: "Security Officer" },
    job_field_description: { en: "" },
    job_field_department_id: 9,
    job_field_parent_id: 13,
    job_field_active: true,
  },

  /*  IT  */
  {
    job_field_id: 15,
    job_field_name: { en: "IT Director" },
    job_field_description: { en: "" },
    job_field_department_id: 10,
    job_field_parent_id: 0,
    job_field_active: true,
  },
  {
    job_field_id: 16,
    job_field_name: { en: "IT Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 10,
    job_field_parent_id: 15,
    job_field_active: true,
  },
  {
    job_field_id: 17,
    job_field_name: { en: "Infrastructure Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 11,
    job_field_parent_id: 15,
    job_field_active: true,
  },
  {
    job_field_id: 18,
    job_field_name: { en: "Systems Engineer" },
    job_field_description: { en: "" },
    job_field_department_id: 11,
    job_field_parent_id: 17,
    job_field_active: true,
  },
  {
    job_field_id: 19,
    job_field_name: { en: "Network Administrator" },
    job_field_description: { en: "" },
    job_field_department_id: 11,
    job_field_parent_id: 18,
    job_field_active: true,
  },
  {
    job_field_id: 20,
    job_field_name: { en: "Development Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 12,
    job_field_parent_id: 15,
    job_field_active: true,
  },
  {
    job_field_id: 21,
    job_field_name: { en: "Development Operations" },
    job_field_description: { en: "" },
    job_field_department_id: 12,
    job_field_parent_id: 20,
    job_field_active: true,
  },
  {
    job_field_id: 22,
    job_field_name: { en: "Frontend Engineer" },
    job_field_description: { en: "" },
    job_field_department_id: 12,
    job_field_parent_id: 20,
    job_field_active: true,
  },
  {
    job_field_id: 23,
    job_field_name: { en: "Backend Engineer" },
    job_field_description: { en: "" },
    job_field_department_id: 12,
    job_field_parent_id: 20,
    job_field_active: true,
  },
  {
    job_field_id: 24,
    job_field_name: { en: "IT Support Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 13,
    job_field_parent_id: 15,
    job_field_active: true,
  },
  {
    job_field_id: 25,
    job_field_name: { en: "IT Support Specialist" },
    job_field_description: { en: "" },
    job_field_department_id: 13,
    job_field_parent_id: 24,
    job_field_active: true,
  },
  {
    job_field_id: 26,
    job_field_name: { en: "IT Technician" },
    job_field_description: { en: "" },
    job_field_department_id: 13,
    job_field_parent_id: 25,
    job_field_active: true,
  },
  {
    job_field_id: 27,
    job_field_name: { en: "IT Security Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 14,
    job_field_parent_id: 15,
    job_field_active: true,
  },
  {
    job_field_id: 28,
    job_field_name: { en: "Security Analyst" },
    job_field_description: { en: "" },
    job_field_department_id: 14,
    job_field_parent_id: 27,
    job_field_active: true,
  },
  {
    job_field_id: 29,
    job_field_name: { en: "Security Engineer" },
    job_field_description: { en: "" },
    job_field_department_id: 14,
    job_field_parent_id: 28,
    job_field_active: true,
  },

  /*  Repair Center  */
  {
    job_field_id: 30,
    job_field_name: { en: "Repair Center Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 20,
    job_field_parent_id: 0,
    job_field_active: true,
  },
  {
    job_field_id: 31,
    job_field_name: { en: "Operations Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 20,
    job_field_parent_id: 30,
    job_field_active: true,
  },
  {
    job_field_id: 32,
    job_field_name: { en: "Triage Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 21,
    job_field_parent_id: 30,
    job_field_active: true,
  },
  {
    job_field_id: 33,
    job_field_name: { en: "Triage Lead" },
    job_field_description: { en: "" },
    job_field_department_id: 21,
    job_field_parent_id: 32,
    job_field_active: true,
  },
  {
    job_field_id: 34,
    job_field_name: { en: "Triage Technician" },
    job_field_description: { en: "" },
    job_field_department_id: 21,
    job_field_parent_id: 33,
    job_field_active: true,
  },
  {
    job_field_id: 35,
    job_field_name: { en: "Repair Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 22,
    job_field_parent_id: 30,
    job_field_active: true,
  },
  {
    job_field_id: 36,
    job_field_name: { en: "Repair Lead" },
    job_field_description: { en: "" },
    job_field_department_id: 22,
    job_field_parent_id: 35,
    job_field_active: true,
  },
  {
    job_field_id: 37,
    job_field_name: { en: "Repair Technician" },
    job_field_description: { en: "" },
    job_field_department_id: 22,
    job_field_parent_id: 36,
    job_field_active: true,
  },
  {
    job_field_id: 52,
    job_field_name: { en: "Google Repair Lead" },
    job_field_description: { en: "" },
    job_field_department_id: 31,
    job_field_parent_id: 35,
    job_field_active: true,
  },
  {
    job_field_id: 53,
    job_field_name: { en: "Senior Repair Technician" },
    job_field_description: { en: "" },
    job_field_department_id: 31,
    job_field_parent_id: 52,
    job_field_active: true,
  },
  {
    job_field_id: 54,
    job_field_name: { en: "Samsung Repair Lead" },
    job_field_description: { en: "" },
    job_field_department_id: 32,
    job_field_parent_id: 35,
    job_field_active: true,
  },
  {
    job_field_id: 55,
    job_field_name: { en: "Senior Repair Technician" },
    job_field_description: { en: "" },
    job_field_department_id: 32,
    job_field_parent_id: 54,
    job_field_active: true,
  },
  {
    job_field_id: 56,
    job_field_name: { en: "Non-phone Repair Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 33,
    job_field_parent_id: 30,
    job_field_active: true,
  },
  {
    job_field_id: 57,
    job_field_name: { en: "Non-phone Specialist" },
    job_field_description: { en: "" },
    job_field_department_id: 33,
    job_field_parent_id: 56,
    job_field_active: true,
  },
  {
    job_field_id: 58,
    job_field_name: { en: "Non-phone Repair Supervisor" },
    job_field_description: { en: "Home device Supervisor" },
    job_field_department_id: 34,
    job_field_parent_id: 56,
    job_field_active: true,
  },
  {
    job_field_id: 59,
    job_field_name: { en: "Non-phone Technician" },
    job_field_description: { en: "Home device technician" },
    job_field_department_id: 34,
    job_field_parent_id: 58,
    job_field_active: true,
  },
  {
    job_field_id: 60,
    job_field_name: { en: "Non-phone Repair Supervisor" },
    job_field_description: { en: "Wearables device Supervisor" },
    job_field_department_id: 35,
    job_field_parent_id: 56,
    job_field_active: true,
  },
  {
    job_field_id: 61,
    job_field_name: { en: "Non-phone Technician" },
    job_field_description: { en: "Wearables device technician" },
    job_field_department_id: 35,
    job_field_parent_id: 60,
    job_field_active: true,
  },
  {
    job_field_id: 62,
    job_field_name: { en: "Non-phone Repair Supervisor" },
    job_field_description: { en: "Accessories device Supervisor" },
    job_field_department_id: 36,
    job_field_parent_id: 56,
    job_field_active: true,
  },
  {
    job_field_id: 63,
    job_field_name: { en: "Non-phone Technician" },
    job_field_description: { en: "Accessories device technician" },
    job_field_department_id: 36,
    job_field_parent_id: 62,
    job_field_active: true,
  },
  {
    job_field_id: 38,
    job_field_name: { en: "QC Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 23,
    job_field_parent_id: 30,
    job_field_active: true,
  },
  {
    job_field_id: 39,
    job_field_name: { en: "QC Supervisor" },
    job_field_description: { en: "" },
    job_field_department_id: 23,
    job_field_parent_id: 38,
    job_field_active: true,
  },
  {
    job_field_id: 40,
    job_field_name: { en: "QA Inspector" },
    job_field_description: { en: "" },
    job_field_department_id: 23,
    job_field_parent_id: 39,
    job_field_active: true,
  },
  {
    job_field_id: 41,
    job_field_name: { en: "Harvest Supervisor" },
    job_field_description: { en: "" },
    job_field_department_id: 24,
    job_field_parent_id: 30,
    job_field_active: true,
  },
  {
    job_field_id: 42,
    job_field_name: { en: "Disassembly Technician" },
    job_field_description: { en: "" },
    job_field_department_id: 24,
    job_field_parent_id: 41,
    job_field_active: true,
  },
  {
    job_field_id: 43,
    job_field_name: { en: "Polishing Supervisor" },
    job_field_description: { en: "" },
    job_field_department_id: 25,
    job_field_parent_id: 30,
    job_field_active: false,
  },
  {
    job_field_id: 44,
    job_field_name: { en: "Polishing Operator" },
    job_field_description: { en: "" },
    job_field_department_id: 25,
    job_field_parent_id: 43,
    job_field_active: false,
  },
  {
    job_field_id: 45,
    job_field_name: { en: "Packaging Supervisor" },
    job_field_description: { en: "" },
    job_field_department_id: 26,
    job_field_parent_id: 30,
    job_field_active: true,
  },
  {
    job_field_id: 46,
    job_field_name: { en: "Packaging Operator" },
    job_field_description: { en: "" },
    job_field_department_id: 26,
    job_field_parent_id: 45,
    job_field_active: true,
  },
  {
    job_field_id: 47,
    job_field_name: { en: "Inventory Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 27,
    job_field_parent_id: 30,
    job_field_active: true,
  },
  {
    job_field_id: 48,
    job_field_name: { en: "Inventory Specialist" },
    job_field_description: { en: "" },
    job_field_department_id: 27,
    job_field_parent_id: 47,
    job_field_active: true,
  },
  {
    job_field_id: 49,
    job_field_name: { en: "Inventory Clerk" },
    job_field_description: { en: "" },
    job_field_department_id: 27,
    job_field_parent_id: 48,
    job_field_active: true,
  },
  {
    job_field_id: 50,
    job_field_name: { en: "Equipment Maintenance Lead" },
    job_field_description: { en: "" },
    job_field_department_id: 28,
    job_field_parent_id: 30,
    job_field_active: true,
  },
  {
    job_field_id: 51,
    job_field_name: { en: "Diagnostic Specialist" },
    job_field_description: { en: "" },
    job_field_department_id: 28,
    job_field_parent_id: 50,
    job_field_active: true,
  },

  /*  Logistics  */
  {
    job_field_id: 71,
    job_field_name: { en: "Logistics Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 70,
    job_field_parent_id: 0,
    job_field_active: true,
  },
  {
    job_field_id: 72,
    job_field_name: { en: "Logistics Coordinator" },
    job_field_description: { en: "" },
    job_field_department_id: 70,
    job_field_parent_id: 71,
    job_field_active: true,
  },
  {
    job_field_id: 73,
    job_field_name: { en: "Warehouse Manager" },
    job_field_description: { en: "" },
    job_field_department_id: 71,
    job_field_parent_id: 71,
    job_field_active: true,
  },
  {
    job_field_id: 74,
    job_field_name: { en: "Warehouse Supervisor" },
    job_field_description: { en: "" },
    job_field_department_id: 71,
    job_field_parent_id: 73,
    job_field_active: true,
  },
  {
    job_field_id: 75,
    job_field_name: { en: "Warehouse Operator" },
    job_field_description: { en: "" },
    job_field_department_id: 71,
    job_field_parent_id: 74,
    job_field_active: true,
  },
  {
    job_field_id: 76,
    job_field_name: { en: "Inbound Supervisor" },
    job_field_description: { en: "" },
    job_field_department_id: 72,
    job_field_parent_id: 71,
    job_field_active: true,
  },
  {
    job_field_id: 77,
    job_field_name: { en: "Receiving Clerk" },
    job_field_description: { en: "" },
    job_field_department_id: 72,
    job_field_parent_id: 76,
    job_field_active: true,
  },
  {
    job_field_id: 78,
    job_field_name: { en: "Outbound Supervisor" },
    job_field_description: { en: "" },
    job_field_department_id: 73,
    job_field_parent_id: 71,
    job_field_active: true,
  },
  {
    job_field_id: 79,
    job_field_name: { en: "Shipping Coordinator" },
    job_field_description: { en: "" },
    job_field_department_id: 73,
    job_field_parent_id: 78,
    job_field_active: true,
  },
];

export const allJobFieldsMock: DbJobField[] = [
  /*  Company  */
  {
    job_field_id: 0,
    job_field_name: { en: "Company" },
    job_field_description: { en: "" },
    job_field_department_id: 0,
    job_field_parent_id: null,
    job_field_active: true,
  },
  ...jobFieldsMock,
];
