import { DbCategory } from "@/api/serviceDesk/category";

const accountAccessCategoryMock = {
  category_id: 11,
  category_name: {
    en: "Account & Access",
    es: "Cuenta y Acceso",
    fr: "Compte et Accès",
    ko: "계정 & 접근",
  },
  category_description: {
    en: "This category is for requesting new accounts, access permissions, or resolving issues related to existing accounts.",
    es: "Esta categoría se utiliza para solicitar nuevas cuentas, permisos de acceso o resolver problemas relacionados con cuentas existentes.",
    fr: "Cette catégorie permet de demander de nouveaux comptes, des autorisations d’accès ou de résoudre des problèmes liés aux comptes existants.",
    ko: "새로운 계정이나 권한을 요청하거나 기존 계정에 관련된 문제 또는 권한 변경과 관련된 카테고리입니다.",
  },
  category_request_template: { en: "", es: "", fr: "", ko: "" },
  category_index: 1,
  category_active: true,
  category_scope: "INTERNAL",
  default_priority: "high",
  default_risk_level: "high",
  default_sla_days: 2,
  sub_category: [
    {
      category_id: 12,
      category_name: {
        en: "New account request",
        es: "Solicitud de nueva cuenta",
        fr: "Demande de nouveau compte",
        ko: "새로운 계정 요청",
      },
      category_description: {
        en: "Request the creation of a new account for an employee.",
        es: "Solicite la creación de una nueva cuenta para un empleado.",
        fr: "Demandez la création d’un nouveau compte pour un employé.",
        ko: "임직원에 대한 새로운 계정을 요청합니다.",
      },
      category_request_template: {
        en: "Please include employee details such as name, department, and required access.",
        es: "Incluya la información del empleado, como nombre, departamento y accesos necesarios.",
        fr: "Veuillez inclure les informations de l’employé, telles que le nom, le service et les accès requis.",
        ko: "임직원에 관련된 정보를 포함하여 요청해주세요.",
      },
      category_index: 1,
      category_active: true,
      default_priority: "medium",
      default_risk_level: "medium",
      default_sla_days: 3,
    },
    {
      category_id: 13,
      category_name: {
        en: "Access permission change",
        es: "Cambio de permisos de acceso",
        fr: "Modification des autorisations d’accès",
        ko: "계정 권한 변경",
      },
      category_description: {
        en: "Request changes to access permissions for an existing account.",
        es: "Solicite cambios en los permisos de acceso de una cuenta existente.",
        fr: "Demandez des modifications des autorisations d’accès pour un compte existant.",
        ko: "기존 계정의 권한 변경을 요청합니다.",
      },
      category_request_template: {
        en: "Please include the account information and details of the required permission changes.",
        es: "Incluya la información de la cuenta y los detalles de los cambios de permisos requeridos.",
        fr: "Veuillez inclure les informations du compte et les détails des modifications d’autorisations demandées.",
        ko: "권한을 변경할 계정 정보를 포함하여 요청해주세요.",
      },
      category_index: 2,
      category_active: true,
      default_priority: null,
      default_risk_level: null,
      default_sla_days: null,
    },
    {
      category_id: 14,
      category_name: {
        en: "Role / group assignment",
        es: "Asignación de roles / grupos",
        fr: "Attribution de rôles / groupes",
        ko: "개인 / 그룹 권한 할당",
      },
      category_description: {
        en: "Request assignment or modification of roles or group permissions for an existing account.",
        es: "Solicite la asignación o modificación de roles o permisos de grupo para una cuenta existente.",
        fr: "Demandez l’attribution ou la modification de rôles ou de permissions de groupe pour un compte existant.",
        ko: "기존 계정의 개인 / 그룹 권한을 부여하거나 수정을 요청합니다.",
      },
      category_request_template: {
        en: "Please include the account information and the roles or groups to be assigned or updated.",
        es: "Incluya la información de la cuenta y los roles o grupos que deben asignarse o modificarse.",
        fr: "Veuillez inclure les informations du compte ainsi que les rôles ou groupes à attribuer ou modifier.",
        ko: "권한을 변경할 계정 정보를 포함하여 요청해주세요.",
      },
      category_index: 3,
      category_active: true,
      default_priority: "medium",
      default_risk_level: null,
      default_sla_days: null,
    },
    {
      category_id: 15,
      category_name: {
        en: "Password reset / MFA issue",
        es: "Restablecimiento de contraseña / problema de MFA",
        fr: "Réinitialisation du mot de passe / problème MFA",
        ko: "비밀번호 초기화 / 다단계 인증 문제",
      },
      category_description: {
        en: "Request a password reset or report issues related to multi-factor authentication.",
        es: "Solicite un restablecimiento de contraseña o informe problemas relacionados con la autenticación multifactor.",
        fr: "Demandez une réinitialisation du mot de passe ou signalez des problèmes liés à l’authentification multifacteur.",
        ko: "기존 계정의 로그인에 문제가 있는 경우, 비밀번호 초기화를 요청할 수 있습니다.",
      },
      category_request_template: {
        en: "Please include the affected account information and a description of the issue.",
        es: "Incluya la información de la cuenta afectada y una descripción del problema.",
        fr: "Veuillez inclure les informations du compte concerné et une description du problème.",
        ko: "로그인에 문제가 있는 계정 정보를 포함하여 요청해주세요.",
      },
      category_index: 4,
      category_active: true,
      default_priority: "urgent",
      default_risk_level: null,
      default_sla_days: 1,
    },
    {
      category_id: 16,
      category_name: {
        en: "Account lock / unlock",
        es: "Bloqueo / desbloqueo de cuenta",
        fr: "Verrouillage / déverrouillage du compte",
        ko: "계정 잠금 / 해제",
      },
      category_description: {
        en: "Request account deactivation for departed employees or reactivation for returning employees.",
        es: "Solicite la desactivación de cuentas de empleados que han salido o la reactivación de cuentas de empleados que regresan.",
        fr: "Demandez la désactivation des comptes des employés sortants ou la réactivation des comptes des employés de retour.",
        ko: "퇴사한 직원의 계정의 비활성화를 요청하거나, 재입사한 직원의 계정의 활성화를 요청합니다.",
      },
      category_request_template: {
        en: "Please include the account information and indicate whether the account should be locked or unlocked.",
        es: "Incluya la información de la cuenta e indique si debe bloquearse o desbloquearse.",
        fr: "Veuillez inclure les informations du compte et préciser s’il doit être verrouillé ou déverrouillé.",
        ko: "잠금 또는 해제할 계정의 정보를 포함하여 요청해주세요.",
      },
      category_index: 5,
      category_active: true,
      default_priority: null,
      default_risk_level: null,
      default_sla_days: 1,
    },
    {
      category_id: 17,
      category_name: {
        en: "Email account issue",
        es: "Problema con la cuenta de correo electrónico",
        fr: "Problème de compte e-mail",
        ko: "이메일 계정 관련",
      },
      category_description: {
        en: "Request assistance for issues related to an email account.",
        es: "Solicite asistencia para problemas relacionados con una cuenta de correo electrónico.",
        fr: "Demandez de l’assistance pour des problèmes liés à un compte de messagerie.",
        ko: "이메일에 관하여 문제가 발생한 계정에 대해 해결을 요청합니다.",
      },
      category_request_template: {
        en: "Please include the account information and the email address affected by the issue.",
        es: "Incluya la información de la cuenta y la dirección de correo electrónico afectada.",
        fr: "Veuillez inclure les informations du compte et l’adresse e-mail concernée.",
        ko: "해결을 요청할 계정 정보와 이메일 주소를 포함하여 요청해주세요.",
      },
      category_index: 6,
      category_active: true,
      default_priority: "medium",
      default_risk_level: null,
      default_sla_days: null,
    },
  ],
} satisfies DbCategory;

export default accountAccessCategoryMock;
