import { DbCategory } from "@/api/serviceDesk/category";

const hardwareDeviceCategoryMock = {
  category_id: 21,
  category_name: {
    en: "Hardware & Device",
    es: "Hardware y Dispositivos",
    fr: "Matériel et Appareils",
    ko: "하드웨어 & 기기",
  },
  category_description: {
    en: "Requests and issue resolution related to PCs, laptops, mobile devices, and peripheral hardware.",
    es: "Solicitudes y resolución de problemas relacionados con PCs, portátiles, dispositivos móviles y hardware periférico.",
    fr: "Demandes et résolution de problèmes liés aux PC, ordinateurs portables, appareils mobiles et périphériques.",
    ko: "PC, 노트북, 모바일 등 하드웨어 및 주변 기기에 관한 요청과 문제 해결을 위한 카테고리입니다.",
  },
  category_request_template: { en: "", es: "", fr: "", ko: "" },
  category_index: 2,
  category_active: true,
  category_scope: "INTERNAL",
  default_priority: "medium",
  default_risk_level: "low",
  default_sla_days: 3,
  sub_category: [
    {
      category_id: 22,
      category_name: {
        en: "New device request (PC / Laptop / Mobile)",
        es: "Solicitud de nuevo dispositivo (PC / Portátil / Móvil)",
        fr: "Demande de nouvel appareil (PC / Ordinateur portable / Mobile)",
        ko: "새로운 기기 요청",
      },
      category_description: {
        en: "Request a new device required for work purposes.",
        es: "Solicite un nuevo dispositivo necesario para fines laborales.",
        fr: "Demande d’un nouvel appareil nécessaire pour le travail.",
        ko: "부서에 추가로 필요한 기기를 요청합니다.",
      },
      category_request_template: {
        en: "Please include the type of device and department information.",
        es: "Incluya el tipo de dispositivo y la información del departamento.",
        fr: "Veuillez inclure le type d’appareil et les informations du service.",
        ko: "필요한 기기와 부서정보를 포함하여 요청해주세요.",
      },
      category_index: 1,
      category_active: true,
      default_priority: null,
      default_risk_level: null,
      default_sla_days: null,
    },
    {
      category_id: 23,
      category_name: {
        en: "Peripheral issue (monitor / mouse / keyboard)",
        es: "Problema de periféricos (monitor / ratón / teclado)",
        fr: "Problème de périphérique (écran / souris / clavier)",
        ko: "주변 기기 문제",
      },
      category_description: {
        en: "Report issues or request replacement for peripheral devices.",
        es: "Informe problemas o solicite el reemplazo de dispositivos periféricos.",
        fr: "Signaler un problème ou demander le remplacement d’un périphérique.",
        ko: "부서에 추가로 필요한 주변 기기를 요청합니다.",
      },
      category_request_template: {
        en: "Please include the peripheral type and department information.",
        es: "Incluya el tipo de periférico y la información del departamento.",
        fr: "Veuillez inclure le type de périphérique et les informations du service.",
        ko: "필요한 주변 기기와 부서정보를 포함하여 요청해주세요.",
      },
      category_index: 2,
      category_active: true,
      default_priority: null,
      default_risk_level: null,
      default_sla_days: 2,
    },
    {
      category_id: 24,
      category_name: {
        en: "Device replacement",
        es: "Reemplazo de dispositivo",
        fr: "Remplacement d’appareil",
        ko: "기기 교체 요청",
      },
      category_description: {
        en: "Request a replacement for a device that is damaged or malfunctioning.",
        es: "Solicite el reemplazo de un dispositivo dañado o con fallas.",
        fr: "Demande de remplacement d’un appareil défectueux ou endommagé.",
        ko: "기존 기기에 문제가 있는 경우 교체를 요청합니다.",
      },
      category_request_template: {
        en: "Please include the device details and department information.",
        es: "Incluya los detalles del dispositivo y la información del departamento.",
        fr: "Veuillez inclure les détails de l’appareil et les informations du service.",
        ko: "교체를 요청할 기기와 부서 정보를 포함하여 요청해주세요.",
      },
      category_index: 3,
      category_active: true,
      default_priority: "high",
      default_risk_level: "medium",
      default_sla_days: null,
    },
    {
      category_id: 25,
      category_name: {
        en: "Device relocation",
        es: "Reubicación de dispositivo",
        fr: "Déplacement d’appareil",
        ko: "기기 재배치",
      },
      category_description: {
        en: "Request relocation of a device to a different location.",
        es: "Solicite la reubicación de un dispositivo a otra ubicación.",
        fr: "Demande de déplacement d’un appareil vers un autre emplacement.",
        ko: "기기 배치를 변경해야 하는 경우 재배치를 요청합니다.",
      },
      category_request_template: {
        en: "Please include the device details and new location information.",
        es: "Incluya los detalles del dispositivo y la nueva ubicación.",
        fr: "Veuillez inclure les détails de l’appareil et la nouvelle localisation.",
        ko: "재배치가 필요한 기기와 위치 정보를 포함하여 요청해주세요.",
      },
      category_index: 4,
      category_active: true,
      default_priority: null,
      default_risk_level: null,
      default_sla_days: null,
    },
    {
      category_id: 26,
      category_name: {
        en: "Device setup / imaging",
        es: "Configuración / Imagen del dispositivo",
        fr: "Configuration / Image système",
        ko: "기기 설정 / 이미징",
      },
      category_description: {
        en: "Request device setup, configuration, or OS imaging.",
        es: "Solicite la configuración del dispositivo o la instalación de imagen del sistema.",
        fr: "Demande de configuration de l’appareil ou d’imagerie du système.",
        ko: "기기에 설정에 변경 혹은 오류가 있는 경우 설정을 요청합니다.",
      },
      category_request_template: {
        en: "Please include the device information and required setup details.",
        es: "Incluya la información del dispositivo y los detalles de configuración.",
        fr: "Veuillez inclure les informations de l’appareil et les détails requis.",
        ko: "설정이 필요한 기기 정보를 포함하여 요청해주세요.",
      },
      category_index: 5,
      category_active: true,
      default_priority: null,
      default_risk_level: "medium",
      default_sla_days: null,
    },
    {
      category_id: 27,
      category_name: {
        en: "Asset inventory update",
        es: "Actualización del inventario de activos",
        fr: "Mise à jour de l’inventaire des actifs",
        ko: "자산 목록 갱신",
      },
      category_description: {
        en: "Request an update to hardware asset inventory records.",
        es: "Solicite la actualización de los registros de inventario de activos de hardware.",
        fr: "Demande de mise à jour des registres d’inventaire du matériel.",
        ko: "갱신이 필요한 자산 목록에 대해 요청합니다.",
      },
      category_request_template: {
        en: "Please include the asset information that needs to be updated.",
        es: "Incluya la información del activo que necesita actualización.",
        fr: "Veuillez inclure les informations de l’actif à mettre à jour.",
        ko: "갱신이 필요한 자산 정보를 포함하여 요청해주세요.",
      },
      category_index: 6,
      category_active: true,
      default_priority: null,
      default_risk_level: null,
      default_sla_days: null,
    },
  ],
} satisfies DbCategory;

export default hardwareDeviceCategoryMock;
