import { DbCategory } from "@/api/serviceDesk/category";

const networkConnectivityCategoryMock = {
  category_id: 41,
  category_name: {
    en: "Network & Connectivity",
    es: "Red y Conectividad",
    fr: "Réseau et Connectivité",
    ko: "네트워크 & 연결",
  },
  category_description: {
    en: "Request support for internet, network, or device connectivity-related issues.",
    es: "Solicite soporte para problemas relacionados con internet, red o conectividad de dispositivos.",
    fr: "Demandez de l’assistance pour les problèmes liés à Internet, au réseau ou à la connectivité des appareils.",
    ko: "인터넷 네트워크 또는 기기 연결에 관한 문제 해결을 요청합니다.",
  },
  category_request_template: { en: "", es: "", fr: "", ko: "" },
  category_index: 4,
  category_active: true,
  category_scope: "INTERNAL",
  default_priority: "high",
  default_risk_level: "high",
  default_sla_days: 1,
  sub_category: [
    {
      category_id: 42,
      category_name: {
        en: "Internet connectivity issue",
        es: "Problema de conectividad a Internet",
        fr: "Problème de connexion Internet",
        ko: "인터넷 연결 문제",
      },
      category_description: {
        en: "Request assistance when internet access is unavailable or disconnected.",
        es: "Solicite asistencia cuando no haya acceso a Internet o la conexión esté interrumpida.",
        fr: "Demandez de l’assistance lorsque l’accès à Internet est indisponible ou interrompu.",
        ko: "인터넷 연결을 할 수 없는 문제에 대해 해결을 요청합니다.",
      },
      category_request_template: {
        en: "Please include the affected device and location details.",
        es: "Incluya el dispositivo afectado y la información de ubicación.",
        fr: "Veuillez inclure l’appareil concerné et les informations de localisation.",
        ko: "문제가 발생한 기기와 위치 정보를 포함하여 요청해주세요.",
      },
      category_index: 1,
      category_active: true,
      default_priority: "urgent",
      default_risk_level: null,
      default_sla_days: null,
    },
    {
      category_id: 43,
      category_name: {
        en: "VPN issue",
        es: "Problema de VPN",
        fr: "Problème de VPN",
        ko: "VPN 문제",
      },
      category_description: {
        en: "Request support for VPN connection or authentication issues.",
        es: "Solicite soporte para problemas de conexión o autenticación VPN.",
        fr: "Demandez de l’assistance pour les problèmes de connexion ou d’authentification VPN.",
        ko: "VPN 연결을 할 수 없는 문제에 대해 해결을 요청합니다.",
      },
      category_request_template: {
        en: "Please include the device, network, and VPN connection details.",
        es: "Incluya el dispositivo, la red y los detalles de la conexión VPN.",
        fr: "Veuillez inclure l’appareil, le réseau et les détails de la connexion VPN.",
        ko: "문제가 발생한 기기와 위치 정보를 포함하여 요청해주세요.",
      },
      category_index: 2,
      category_active: true,
      default_priority: "urgent",
      default_risk_level: null,
      default_sla_days: null,
    },
    {
      category_id: 44,
      category_name: {
        en: "Wi-Fi issue",
        es: "Problema de Wi-Fi",
        fr: "Problème de Wi-Fi",
        ko: "Wi-Fi 문제",
      },
      category_description: {
        en: "Request assistance for Wi-Fi or wireless network connection issues.",
        es: "Solicite asistencia para problemas de conexión Wi-Fi o red inalámbrica.",
        fr: "Demandez de l’assistance pour les problèmes de connexion Wi-Fi ou réseau sans fil.",
        ko: "Wi-Fi 혹은 무선 연결 문제에 대해 해결을 요청합니다.",
      },
      category_request_template: {
        en: "Please include the Wi-Fi network name, device, and location.",
        es: "Incluya el nombre de la red Wi-Fi, el dispositivo y la ubicación.",
        fr: "Veuillez inclure le nom du réseau Wi-Fi, l’appareil et la localisation.",
        ko: "문제가 발생한 Wi-Fi 혹은 무선 연결 기기와 위치 정보를 포함하여 요청해주세요.",
      },
      category_index: 3,
      category_active: true,
      default_priority: null,
      default_risk_level: "medium",
      default_sla_days: null,
    },
    {
      category_id: 45,
      category_name: {
        en: "Network performance issue",
        es: "Problema de rendimiento de red",
        fr: "Problème de performance réseau",
        ko: "네트워크 성능 문제",
      },
      category_description: {
        en: "Request support for slow, unstable, or unresponsive network connections.",
        es: "Solicite soporte para conexiones de red lentas, inestables o sin respuesta.",
        fr: "Demandez de l’assistance pour des connexions réseau lentes, instables ou non réactives.",
        ko: "인터넷 네트워크 혹은 기기 연결이 불안정하거나 응답이 없는 문제에 대해 해결을 요청합니다.",
      },
      category_request_template: {
        en: "Please include the affected network or device details.",
        es: "Incluya los detalles de la red o del dispositivo afectado.",
        fr: "Veuillez inclure les détails du réseau ou de l’appareil concerné.",
        ko: "점검이 필요한 네트워크 정보나 기기 정보를 포함하여 요청해주세요.",
      },
      category_index: 4,
      category_active: true,
      default_priority: null,
      default_risk_level: null,
      default_sla_days: 2,
    },
    {
      category_id: 46,
      category_name: {
        en: "Firewall / IP request",
        es: "Solicitud de firewall / IP",
        fr: "Demande de pare-feu / IP",
        ko: "방화벽 / IP 요청",
      },
      category_description: {
        en: "Request support for firewall restrictions or IP address changes or additions.",
        es: "Solicite soporte para restricciones de firewall o cambios o adiciones de direcciones IP.",
        fr: "Demandez de l’assistance pour les restrictions de pare-feu ou les modifications ou ajouts d’adresses IP.",
        ko: "방화벽으로 인한 문제나 IP 추가, 이동이 필요한 경우 해결을 요청합니다.",
      },
      category_request_template: {
        en: "Please include the device information and required IP or firewall details.",
        es: "Incluya la información del dispositivo y los detalles de IP o firewall requeridos.",
        fr: "Veuillez inclure les informations de l’appareil et les détails IP ou pare-feu requis.",
        ko: "해결이 필요한 PC 정보를 포함하여 요청해주세요.",
      },
      category_index: 5,
      category_active: true,
      default_priority: "medium",
      default_risk_level: null,
      default_sla_days: 3,
    },
  ],
} satisfies DbCategory;

export default networkConnectivityCategoryMock;
