import {
  BookOpen,
  CalendarRange,
  ChartLine,
  CircleUserRound,
  CodeXml,
  Contact,
  FileText,
  History,
  Home,
  ListCollapse,
  ListTree,
  LucideIcon,
  Palette,
  Paperclip,
  RectangleEllipsis,
  Settings,
  Shapes,
  SquareStack,
  Ticket,
  Tickets,
  User,
  UserCog,
  UserKey,
  UserRoundCog,
  UserStar,
} from "lucide-react";

/** Maps icon identifiers persisted by the menu API to supported UI icons. */
export const leftMenuIconMap: Record<string, LucideIcon> = {
  BookOpen,
  CalendarRange,
  ChartLine,
  CircleUserRound,
  CodeXml,
  Contact,
  FileText,
  History,
  Home,
  ListCollapse,
  ListTree,
  Palette,
  Paperclip,
  RectangleEllipsis,
  Settings,
  Shapes,
  SquareStack,
  Ticket,
  Tickets,
  User,
  UserCog,
  UserKey,
  UserRoundCog,
  UserStar,
};

export function getLeftMenuIcon(iconKey: string): LucideIcon {
  // Unknown persisted keys must not break navigation rendering.
  return leftMenuIconMap[iconKey] ?? Home;
}
