export const IT_SERVICE_DESK_KEY = "IT-SERVICE-DESK";
export const IT_SERVICE_DESK_APPROVAL_STEP_KEY =
  "IT-SERVICE-DESK-APPROVAL_STEP";
export const IT_SERVICE_DESK_CATEGORY_KEY = "IT-SERVICE-DESK-CATEGORY";
export const IT_SERVICE_DESK_ASSIGNMENT_RULE_KEY =
  "IT-SERVICE-DESK-ASSIGNMENT-RULE";
